# Generated by Django 3.1.2 on 2020-10-29 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201029_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='slug',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
