# Generated by Django 3.1.2 on 2020-11-08 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20201029_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiguide',
            name='overview',
            field=models.TextField(blank=True, null=True),
        ),
    ]
