# Generated by Django 3.1.2 on 2020-11-10 14:56

import ckeditor.fields
from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_apiguide_overview'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('overview', models.TextField(blank=True, null=True)),
                ('about', ckeditor.fields.RichTextField()),
                ('image', models.ImageField(upload_to=main.utils.get_image_name)),
            ],
        ),
    ]
