# Generated by Django 3.1.2 on 2020-11-16 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20201116_0401'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
