# Generated by Django 3.1.2 on 2020-11-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_suggestion_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='subject',
            field=models.CharField(default='Master Of New World', max_length=255),
            preserve_default=False,
        ),
    ]
