# Generated by Django 3.1.2 on 2020-11-17 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_suggestion_subject'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gmail', models.EmailField(blank=True, max_length=254, null=True)),
                ('outlook', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
