# Generated by Django 3.1.2 on 2020-11-18 05:56

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=main.utils.get_image_name),
        ),
    ]
