# Generated by Django 3.1.2 on 2020-11-18 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_contact_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': 'Contact Info', 'verbose_name_plural': 'Contact Info'},
        ),
    ]
