# Generated by Django 3.1.2 on 2020-11-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_siteinfo_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteinfo',
            name='title',
            field=models.CharField(default='Find Your API ', max_length=255),
            preserve_default=False,
        ),
    ]
