# Generated by Django 3.1.2 on 2020-11-19 11:45

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20201119_1058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteinfo',
            name='name',
        ),
        migrations.AlterField(
            model_name='siteinfo',
            name='about',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
