# Generated by Django 3.1.2 on 2020-11-24 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20201119_1145'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteinfo',
            name='portfolio',
            field=models.URLField(blank=True, null=True),
        ),
    ]
