# Generated by Django 3.1.2 on 2020-11-24 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_siteinfo_portfolio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinfo',
            old_name='portfolio',
            new_name='portfolio_url',
        ),
    ]
