# Generated by Django 3.1.2 on 2020-11-25 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20201124_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='siteinfo',
            old_name='about',
            new_name='main_content',
        ),
    ]
