# Generated by Django 3.1.2 on 2020-11-27 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20201125_0733'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apiguide',
            options={'verbose_name': 'API Guide', 'verbose_name_plural': 'API Guides'},
        ),
    ]
