# Generated by Django 3.1.2 on 2020-11-28 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_auto_20201127_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiguide',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
