# Generated by Django 3.1.2 on 2020-10-31 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapimodel',
            old_name='second_name',
            new_name='last_name',
        ),
    ]
