# Generated by Django 3.1.2 on 2020-12-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0002_auto_20201210_2115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postapimodel',
            name='thumbnail',
        ),
        migrations.AddField(
            model_name='postapimodel',
            name='thumbnail_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
