# Generated by Django 3.1.2 on 2020-10-31 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0003_remove_userapimodel_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapimodel',
            old_name='city',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='userapimodel',
            old_name='street',
            new_name='birth_place',
        ),
        migrations.RemoveField(
            model_name='userapimodel',
            name='suite',
        ),
        migrations.RemoveField(
            model_name='userapimodel',
            name='zipcode',
        ),
        migrations.AddField(
            model_name='userapimodel',
            name='email',
            field=models.EmailField(default='\tSan Diego, CA, USA', max_length=254),
            preserve_default=False,
        ),
    ]
