# Generated by Django 3.1.2 on 2020-11-01 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0004_auto_20201031_1017'),
    ]

    operations = [
        migrations.AddField(
            model_name='userapimodel',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
