# Generated by Django 3.1.2 on 2020-12-16 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_auto_20201216_2116'),
    ]

    operations = [
        migrations.RenameField(
            model_name='commentapimodel',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AddField(
            model_name='commentapimodel',
            name='postId',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
