# Generated by Django 3.1.2 on 2020-11-01 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0005_userapimodel_full_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapimodel',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=255),
        ),
    ]
