# Generated by Django 3.1.2 on 2020-12-16 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0006_auto_20201216_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentapimodel',
            name='post',
        ),
    ]
