# Generated by Django 3.1.2 on 2020-11-02 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0007_postapimodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postapimodel',
            name='content',
            field=models.TextField(default='hahah'),
            preserve_default=False,
        ),
    ]
