# Generated by Django 3.1.2 on 2020-11-02 12:03

import apis.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0008_auto_20201102_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postapimodel',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=apis.utils.get_thumnail_name),
        ),
    ]
