# Generated by Django 3.1.2 on 2020-11-02 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20201102_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postapimodel',
            options={'verbose_name': 'Post Api', 'verbose_name_plural': 'Posts Api'},
        ),
    ]
