# Generated by Django 3.1.2 on 2020-12-17 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0009_auto_20201217_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentapimodel',
            name='user_id',
        ),
    ]
