# Generated by Django 3.1.2 on 2020-11-02 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0010_auto_20201102_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postapimodel',
            options={'verbose_name': 'Post', 'verbose_name_plural': 'Posts Api'},
        ),
        migrations.AlterModelOptions(
            name='userapimodel',
            options={'verbose_name': 'User', 'verbose_name_plural': 'Users Api'},
        ),
    ]
