# Generated by Django 3.1.2 on 2020-11-02 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0011_auto_20201102_1205'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postapimodel',
            old_name='author',
            new_name='user',
        ),
    ]
