# Generated by Django 3.1.2 on 2020-11-02 17:57

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_auto_20201102_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='postapimodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postapimodel',
            name='published_at',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 2, 17, 57, 17, 881159, tzinfo=utc)),
        ),
    ]
