# Generated by Django 3.1.2 on 2020-12-17 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0012_auto_20201217_0058'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postapimodel',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='postapimodel',
            name='thumbnail_url',
        ),
        migrations.RemoveField(
            model_name='postapimodel',
            name='updated_at',
        ),
    ]
