# Generated by Django 3.1.2 on 2020-12-17 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0013_auto_20201217_1844'),
    ]

    operations = [
        migrations.AddField(
            model_name='postapimodel',
            name='authorId',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='postapimodel',
            name='author_email',
            field=models.EmailField(default='username', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postapimodel',
            name='author_name',
            field=models.CharField(default='masterbdx@gmail.com', max_length=255),
            preserve_default=False,
        ),
    ]
