# Generated by Django 3.1.2 on 2020-12-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_auto_20201217_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postapimodel',
            name='author_id',
        ),
    ]
