# Generated by Django 3.1.2 on 2020-11-02 17:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0014_auto_20201102_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postapimodel',
            name='published_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
