# Generated by Django 3.1.2 on 2020-12-18 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0015_remove_postapimodel_author_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postapimodel',
            old_name='authorId',
            new_name='author_id',
        ),
    ]
