# Generated by Django 3.1.2 on 2020-11-02 18:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0016_auto_20201102_1802'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postapimodel',
            old_name='user',
            new_name='user_id',
        ),
    ]
