# Generated by Django 3.1.2 on 2020-12-18 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_auto_20201218_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postapimodel',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
