# Generated by Django 3.1.2 on 2020-11-03 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0017_auto_20201102_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommntApiModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apis.postapimodel', verbose_name='posts')),
            ],
            options={
                'verbose_name': 'Comment',
                'verbose_name_plural': 'Comments Api',
            },
        ),
    ]
