# Generated by Django 3.1.2 on 2020-12-18 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_auto_20201218_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentapimodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
