# Generated by Django 3.1.2 on 2020-11-03 12:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0018_commntapimodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='commntapimodel',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='commntapimodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
