# Generated by Django 3.1.2 on 2020-11-03 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0019_auto_20201103_1256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommntApiModel',
            new_name='CommentApiModel',
        ),
    ]
