# Generated by Django 3.1.2 on 2020-12-24 14:21

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0021_auto_20201218_2020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapimodel',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(default='+12125552368', max_length=128, region=None),
        ),
    ]
