# Generated by Django 3.1.2 on 2020-11-04 17:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0021_auto_20201103_1834'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentapimodel',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apis.userapimodel'),
            preserve_default=False,
        ),
    ]
