# Generated by Django 3.1.2 on 2020-11-07 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0022_commentapimodel_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postapimodel',
            old_name='user_id',
            new_name='author_id',
        ),
        migrations.RemoveField(
            model_name='commentapimodel',
            name='email',
        ),
        migrations.RemoveField(
            model_name='commentapimodel',
            name='name',
        ),
    ]
