# Generated by Django 3.1.2 on 2020-11-07 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0023_auto_20201107_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postapimodel',
            name='published_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
