# Generated by Django 3.1.2 on 2020-11-07 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0024_auto_20201107_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentapimodel',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='apis.userapimodel'),
        ),
    ]
