# Generated by Django 3.1.2 on 2020-11-25 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apis', '0025_auto_20201107_2127'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userapimodel',
            name='first_name',
            field=models.CharField(default='what', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userapimodel',
            name='last_name',
            field=models.CharField(default='example', max_length=255),
            preserve_default=False,
        ),
    ]
